version: "3"
services:
 payment-mysql:
  image: library/mysql:8.0
  container_name: 'payment-mysql'
  restart: always
  ports:
    - 3307:3306
  environment:
   MYSQL_ROOT_PASSWORD: 123456
   MYSQL_DATABASE: maccshop
   MYSQL_USER: root
   MYSQL_PASSWORD: root
  networks:
   - microservices
  volumes:
   - ./data/mysql:/var/lib/mysql

 phpmyadmin:
  container_name: 'payment-phpmyadmin'
  image: phpmyadmin/phpmyadmin
  environment:
   PMA_HOST: payment-mysql
   PMA_PORT: 3306
  ports:
   - 8082:80
  networks:
   - microservices
  volumes:
   - /sessions
 
 payment-service:
  build: ./payment
  container_name: 'payment-service'
  restart: always
  networks:
   - microservices
  volumes:
   - ./payment:/usr/src/app
  ports:
   - 5002:80
  depends_on:
   - payment-mysql

networks:
 microservices:
  driver: bridge
#networks:
#  default:
#    external:
#      name: product_service_microservices
