version: "3"
services:
 delivery-mysql:
  image: library/mysql:8.0
  container_name: 'delivery-mysql'
  restart: always
  ports:
    - 3308:3306
  environment:
   MYSQL_ROOT_PASSWORD: 123456
   MYSQL_DATABASE: maccshop
   MYSQL_USER: root
   MYSQL_PASSWORD: root
  networks:
   - microservices
  volumes:
   - ./data/mysql:/var/lib/mysql

 phpmyadmin:
  container_name: 'delivery-phpmyadmin'
  image: phpmyadmin/phpmyadmin
  environment:
   PMA_HOST: delivery-mysql
   PMA_PORT: 3306
  ports:
   - 8083:80
  networks:
   - microservices
  volumes:
   - /sessions
 
 delivery-service:
  build: ./delivery
  container_name: 'delivery-service'
  restart: always
  networks:
   - microservices
  volumes:
   - ./delivery:/usr/src/app
  ports:
   - 5003:80
  depends_on:
   - delivery-mysql

networks:
 microservices:
  driver: bridge

#networks:
#  default:
#    external:
#      name: product_service_microservices
#version: '3'

#services:
#  mongo-express:
#    image: mongo-express
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: renatogroffe
#      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
#    links:
#      - mongo
#    networks:
#      - mongo-compose-network
#
#  mongo:
#    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
#    ports:
#      - "27017:27017"
#    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
#    networks:
#      - mongo-compose-network

#networks:
#    mongo-compose-network:
#      driver: bridge